#!/bin/sh

PYTHON="$1"
ATOM="$2"

# We need to remove the stupid "file://" that Evince puts in front of the file name
# Notice the wild quoting: we need to interpolate $ATOM
# In the end, EDITORCMD should be of the form:
#
# f=%f; atom "${f#file://}:%l"
#
# where atom is the name of the atom binary
EDITORCMD="f=\"%f\"; $ATOM \"\${f#file://}:%l\""

PDFFILE="$3"

if [ -f "$PDFFILE" ];then
	# danke an Feuerfieber
	# http://forum.ubuntuusers.de/topic/evince-synctex-vim-emacs-scite-lyx-kile-editor/#post-2841828
	if [ -f "${PDFFILE%%.pdf}.synctex.gz" ];then
		# we change the cwd to this directory, so this should work
		# also note that we stick in 'python' because the script file need not be executable
		$PYTHON evince_backward_search "$PDFFILE" "$EDITORCMD"&
		BACKWARD_SEARCH_PID=$!
		echo $BACKWARD_SEARCH_PID
	fi
fi

/usr/bin/evince "$3"

if [ "$BACKWARD_SEARCH_PID" ];then
	echo "Killing $BACKWARD_SEARCH_PID"
	kill $BACKWARD_SEARCH_PID
fi
